title: stunningtofu | DevOps
# Hapus semua yang berbau remote_theme: just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Konfigurasi sitemap agar tidak error
defaults:
  - scope:
      path: ""
    values:
      layout: "home"